[tool.poetry]
name = "eth-two-project"
version = "0.1.0"
description = ""
authors = ["Traismer <alekstrais@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
web3 = "^6.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
